export enum SystemRole {
  ADMIN = 'ADMIN',
  EMPLOYEE = 'EMPLOYEE',
}

export enum ProjectPermissionLevel {
  READ = 'READ',
  WRITE = 'WRITE',
}

export enum ChannelType {
  PROJECT_PUBLIC = 'PROJECT_PUBLIC',
  PROJECT_PRIVATE = 'PROJECT_PRIVATE',
  DIRECT_MESSAGE = 'DIRECT_MESSAGE',
}

export enum AccountStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum NotificationType {
  MESSAGE_GROUP = 'MESSAGE_GROUP',
  MESSAGE_DM = 'MESSAGE_DM',
  TASK_CREATED = 'TASK_CREATED',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_APPROVAL_NEEDED = 'TASK_APPROVAL_NEEDED',
  TASK_APPROVED = 'TASK_APPROVED',
  TASK_REJECTED = 'TASK_REJECTED',
}

export enum TaskStatus {
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  REVIEW = 'REVIEW',
  DONE = 'DONE',
}
